set(HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/Batcher/Batch.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Batcher/BatchJobMaster.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/Component.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentCreatorFactory.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/CharacterMovementComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentType.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/DirectionalLightComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/InputComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/LightComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/MoveCompBehaviorVisitor.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/MovementComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/SceneComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/SpotlightComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/Transform.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/ComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/BillboardComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/CubemapComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/DirectionalLightComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/InputComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/LightComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/MeshComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/MovementComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/PhysicsComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/PointLightComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/SkyboxComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/SpotlightComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/ComponentData/WaterPlaneComponentData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PhysicsComponents/CharacterPhysicsComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PhysicsComponents/PhysicsComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/BillboardComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/CubemapComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/PrimitiveComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/SkeletalMeshComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/SkyboxComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/StaticMeshComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/WaterPlaneComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/CameraTransformChangedEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/EventDispatcher.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/KeyboardInputEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/KinematicBodyMovedEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/PhysicsDescriptorRemovedEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/PhysicsSimulationUpdatedEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/PlayerMovedEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/TEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/TextureAtlasGeneratedEvent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/Policy/Policies.h
  ${CMAKE_CURRENT_SOURCE_DIR}/FramebufferImplementation/PlanarReflectionFramebuffer.h
  ${CMAKE_CURRENT_SOURCE_DIR}/FramebufferImplementation/ShadowFramebuffer.h
  ${CMAKE_CURRENT_SOURCE_DIR}/FramebufferImplementation/WaterPlaneFramebuffer.h
  ${CMAKE_CURRENT_SOURCE_DIR}/GameObjectPropertyBindings/AnimationPropertyBinding.h
  ${CMAKE_CURRENT_SOURCE_DIR}/GameObjectPropertyBindings/FloatPropertyBinding.h
  ${CMAKE_CURRENT_SOURCE_DIR}/GameObjectPropertyBindings/PropertyBinding.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Input/InputManager.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Input/KeyboardBindings.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Input/KeyboardData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Input/Keys.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/DebugRender/BulletDebugRenderer.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/DebugRender/DebugPhysicsRenderData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhyBoxShape.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhyCapsuleShape.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhyCompoundShape.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhyPlaneShape.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhysicsShapeBase.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhySphereShape.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/DynamicCharacterController.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/PhysicsDescriptor.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/RigidBodyController.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsWorld.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_Actor.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_EngineBase.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_EngineObjectsCreator.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_MovementComponent.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/EngineObjectCreator.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaCore.inl
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaWrapper.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Serialize/SerializeData/SerializeData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Serialize/SerializeData/SerializeDataContainer.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Serialize/ISerializable.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Serialize/SerializeHelper.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/VertexFactoryImp/SkeletalMeshVertexFactory.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/VertexFactoryImp/SkyboxVertexFactory.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/VertexFactoryImp/StaticMeshVertexFactory.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/BillboardShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CapturePlanarReflectionShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CubemapShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CapturePlanarReflectionShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CubemapShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/DeferredLightShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/DepthCollectShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/PointLightDepthShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/TextureRendererShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/WaterPlaneShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/ShaderCommon.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/SimpleShader.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/AnimationTweenController.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/FloatTweenController.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/ITweenController.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/StateTransition.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/Tweener.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/TweenerParser.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/State.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/StateProperty.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/BindingAttachmentBuilder.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ACamera.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Actor.h
  ${CMAKE_CURRENT_SOURCE_DIR}/BoundingBox.h
  ${CMAKE_CURRENT_SOURCE_DIR}/BoundingBoxBuilder.h
  ${CMAKE_CURRENT_SOURCE_DIR}/FirstPersonCamera.h
  ${CMAKE_CURRENT_SOURCE_DIR}/GameObject.h
  ${CMAKE_CURRENT_SOURCE_DIR}/GlobalSettings.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Level.h
  ${CMAKE_CURRENT_SOURCE_DIR}/MainThirdPersonCamera.h
  ${CMAKE_CURRENT_SOURCE_DIR}/PlayerController.h
  ${CMAKE_CURRENT_SOURCE_DIR}/Scene.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ThirdPersonCamera.h
  ${CMAKE_CURRENT_SOURCE_DIR}/LevelFactory.h
  ${CMAKE_CURRENT_SOURCE_DIR}/ITickable.h
  ${CMAKE_CURRENT_SOURCE_DIR}/LoggerExtension.h
  ${CMAKE_CURRENT_SOURCE_DIR}/GameObjectProperty.h
)

set(SOURCE
  ${CMAKE_CURRENT_SOURCE_DIR}/Batcher/Batch.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Batcher/BatchJobMaster.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/Component.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/CharacterMovementComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/DirectionalLightComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/InputComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/LightComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/MoveCompBehaviorVisitor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/MovementComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/SceneComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/SpotlightComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/Transform.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PhysicsComponents/CharacterPhysicsComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PhysicsComponents/PhysicsComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/BillboardComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/CubemapComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/PrimitiveComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/SkeletalMeshComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/SkyboxComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/StaticMeshComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Components/PrimitiveComponents/WaterPlaneComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Event/TEvent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/FramebufferImplementation/PlanarReflectionFramebuffer.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/FramebufferImplementation/ShadowFramebuffer.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/FramebufferImplementation/WaterPlaneFramebuffer.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/Shapes/PhyCompoundShape.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/DynamicCharacterController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/PhysicsDescriptor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsDescriptors/RigidBodyController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Physics/PhysicsWorld.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_Actor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_EngineBase.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_EngineObjectsCreator.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaExecutors/LuaScriptExecutor_MovementComponent.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/EngineObjectCreator.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ScriptingCore/LuaWrapper.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Serialize/SerializeHelper.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/BillboardShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CapturePlanarReflectionShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CubemapShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CapturePlanarReflectionShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/CubemapShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/DeferredLightShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/DepthCollectShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/PointLightDepthShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/TextureRendererShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ShaderImplementation/WaterPlaneShader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/AnimationTweenController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/FloatTweenController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/ITweenController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/StateTransition.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/Tweener.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Tweener/TweenerParser.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ACamera.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Actor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/BoundingBox.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/BoundingBoxBuilder.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/FirstPersonCamera.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/GameObject.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/GlobalSettings.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Level.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/MainThirdPersonCamera.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/PlayerController.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Scene.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/ThirdPersonCamera.cpp
)

add_library(EngineGameCoreModule STATIC ${HEADERS} ${SOURCE})

set_target_properties(EngineGameCoreModule PROPERTIES LINKER_LANGUAGE CXX)

set(ENGINE_CORE_INCLUDE ${PROJECT_SOURCE_DIR}/PHEngine/src/)
set(GLM_DEPENDENCE_INCLUDE ${PROJECT_SOURCE_DIR}/PHEngine/Dependencies/GLM/include/)
set(CEREAL_DEPENDENCE_INCLUDE ${PROJECT_SOURCE_DIR}/PHEngine/Dependencies/cereal/include/)
set(GLEW_DEPENDENCE_INCLUDE ${PROJECT_SOURCE_DIR}/PHEngine/Dependencies/GLEW/include/)

message(STATUS "GLM_DEPENDENCE_INCLUDE path=${GLM_DEPENDENCE_INCLUDE}")

target_include_directories(EngineGameCoreModule 
  PUBLIC ${ENGINE_CORE_INCLUDE}
  PUBLIC ${GLM_DEPENDENCE_INCLUDE}
  PUBLIC ${CEREAL_DEPENDENCE_INCLUDE}
  PUBLIC ${GLEW_DEPENDENCE_INCLUDE})
