#pragma once

namespace Game {
enum class eGameObjectsCollisionType {
    UNDEFINED,
    SPACESHIP_WITH_MISSILE,
    SPACESHIP_WITH_NEUTRAL_SPACE_OBJECT,
    MISSILE_WITH_NEUTRAL_SPACE_OBJECT,
    MISSILE_WITH_BARRIER,
    ENEMY_MISSILE_WITH_BARRIER
};
}