#pragma once

#include <string>
#include <cstddef>
#include "Core/CommonCore/Assertion.h"

namespace Game
{
   enum ComponentType
   {
      COMPONENT = 1,
      SCENE_COMPONENT = 2,
      PHYSICS_COMPONENT = 4,
      LIGHT_COMPONENT = SCENE_COMPONENT | 8,
      PRIMITIVE_COMPONENT = SCENE_COMPONENT | 16,
      INPUT_COMPONENT = COMPONENT | 32,
      MOVEMENT_COMPONENT = COMPONENT | 64,
      CHARACTER_MOVEMENT_COMPONENT = MOVEMENT_COMPONENT | 128,
      PLATFORM_MOVEMENT_COMPONENT = COMPONENT | 256,
      PLANAR_REFLECTION_COMPONENT = SCENE_COMPONENT | 512
   };
}
