#pragma once

#include <string>
#include <cstddef>
#include "Core/CommonCore/Assertion.h"

namespace EngineCore
{
   enum eComponentType
   {
      COMPONENT = 0x1,
      SCENE_COMPONENT = (COMPONENT << 1) | COMPONENT,
      PHYSICS_COMPONENT = (COMPONENT << 2) | COMPONENT,
      INPUT_COMPONENT = (COMPONENT << 5) | COMPONENT,
      MOVEMENT_COMPONENT = (COMPONENT << 6) | COMPONENT,
      LIGHT_COMPONENT = SCENE_COMPONENT | (COMPONENT << 3),
      PRIMITIVE_COMPONENT = SCENE_COMPONENT | (COMPONENT << 4),
      CHARACTER_MOVEMENT_COMPONENT = (COMPONENT << 7) | MOVEMENT_COMPONENT,
      PLATFORM_MOVEMENT_COMPONENT = COMPONENT | (COMPONENT << 8),
      PLANAR_REFLECTION_COMPONENT = SCENE_COMPONENT | (COMPONENT << 9),
      UI_COMPONENT = (COMPONENT << 10) | COMPONENT
   };
}
