function(findLibraryAndLinkToTarget targetName linkFlag libraryName absPathToLibrary)
    unset(FOUND_LIBRARY CACHE)
    find_library(FOUND_LIBRARY ${libraryName} ${absPathToLibrary})
    if(NOT FOUND_LIBRARY)
        message(FATAL_ERROR "${libraryName} wasn't found for target ${targetName} in ${absPathToLibrary}")
    else()
        message(STATUS "Found ${libraryName} for target ${targetName}.")
        target_link_libraries(${targetName} ${linkFlag} ${FOUND_LIBRARY})
    endif()
    unset(FOUND_LIBRARY CACHE)
endfunction()

function(findLibrariesAndLinkToTarget targetName linkFlag libraryNameList absPathToLibraries)
    foreach(lib_name IN LISTS ${libraryNameList})
        findLibraryAndLinkToTarget(${targetName} ${linkFlag} ${lib_name} ${absPathToLibraries})
    endforeach()
endfunction()
